youtube_datalake:
  target: hive
  outputs:
    hive:
      type: hive
      host: 192.168.1.16
      port: 10000
      schema: youtube_datalake
      # username: <user>
      # password: <pass>

      use_http_transport: true # default value: true
      use_ssl: true # TLS should always be used with LDAP to ensure secure transmission of credentials, default value: true
