
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.4}
  command:
    - -c
    - |
      mkdir -p /sources/logs /sources/dags /sources/plugins
      chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
      exec /entrypoint airflow version
      su airflow -c "pip install unidecode"
      exec /entrypoint airflow version
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 5
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 20
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"

  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:

  hadoop_hive:
    image: hadoop_hive_dbt_container_v4:latest
    container_name: hadoop_hive_dbt_container

    ports:
      - "9870:9870"   # HDFS NameNode
      - "10000:10000" # HiveServer2
      - "10002:10002" # Hive Web UI ou Thrift
      - "8088:8088"   # YARN ResourceManager
      - "7077:7077"   # Spark Master
      - "4040:4040"   # Spark UI
    #    stdin_open: true
    #    tty: true
    volumes:
      - ./datalake:/home/hadoop/datalake
      - ./datalake_youtube_dbt:/home/hadoop/projeto_dbt
      - ./mysql_data:/var/lib/mysql
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      airflow-net:
        ipv4_address: 172.28.0.14

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      TZ: "America/Sao_Paulo"
    volumes:
      - ./postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      airflow-net:
        ipv4_address: 172.28.0.5

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "pip install unidecode && exec airflow webserver"
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-common-env
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      airflow-net:
        ipv4_address: 172.28.0.10

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "pip install unidecode && exec airflow scheduler"
    environment:
      <<: *airflow-common-env
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      airflow-net:
        ipv4_address: 172.28.0.11

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      bash -c "pip install unidecode && mkdir -p /sources/logs /sources/dags /sources/plugins && chown -R \"${AIRFLOW_UID}:0\" /sources/{logs,dags,plugins} && airflow version"
    environment:
      <<: *airflow-common-env
      TZ: "America/Sao_Paulo"
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    networks:
      airflow-net:
        ipv4_address: 172.28.0.12

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug


    command: >
      bash -c "pip install unidecode && exec bash"
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
      TZ: "America/Sao_Paulo"
    networks:
      airflow-net:
        ipv4_address: 172.28.0.13

volumes:
  postgres-db-volume:
  sqlserver-data:

networks:
  airflow-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
