x-airflow-common:
  &airflow-common
  image: airflow-hive:latest
  environment:

    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor  # Mudar para LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__WEBSERVER__SECRET_KEY: "uJ7BQc5eZP29KuyRZVsfRY91SpqI3LCee7zkKTpq6rOHRqCjljjvWDp90oOnc4SP5PhD4uXsmiykKKnzow"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 5
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 20
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__LOGGING__LOGGING_LEVEL: "DEBUG"
    _PIP_ADDITIONAL_REQUIREMENTS: "rich-argparse<1.3.0 unidecode"
    UMASK: "000"  # Corrigido aqui

  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/datalake:/opt/airflow/datalake

  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

networks:
  airflow-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      airflow-net:
        ipv4_address: 172.25.0.16


  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-common-env
      TZ: "America/Sao_Paulo"  # Adicionando configuração de fuso horário
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
          airflow-net:
            ipv4_address: 172.25.0.15


  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      airflow-net:
        ipv4_address: 172.25.0.14


  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chmod -R 777 /sources/{logs,dags,plugins,datalake}
        chmod g+s /sources/{logs,dags,plugins,datalake}
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      TZ: "America/Sao_Paulo"  # Adicionando configuração de fuso horário
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''

    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    networks:
      airflow-net:
        ipv4_address: 172.25.0.13

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
      TZ: "America/Sao_Paulo"  # Adicionando configuração de fuso horário
    command:
      - bash
      - -c
      - airflow

    networks:
      airflow-net:
        ipv4_address: 172.25.0.12


  hive:
    image: hadoop_hive_v5
    container_name: hive_server
    hostname: hive_server
    ports:
      - "10000:10000"   # HiveServer2
      - "10002:10002"   # Beeline (opcional)
      - "9870:9870"     # HDFS Namenode Web UI
      - "9864:9864"     # HDFS Namenode Web UI

    environment:
      - HIVE_METASTORE_HOST=hive-metastore-db
      - HIVE_METASTORE_PORT=9083
      - TZ=America/Sao_Paulo
    volumes:
      - ./datalake:/home/hadoop/datalake
    networks:
      airflow-net:
        ipv4_address: 172.25.0.10

  metastore-db:
    image: mysql:8.0.30
    container_name: hive-metastore-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - ./metastore_db:/var/lib/mysql
    networks:
      airflow-net:
        ipv4_address: 172.25.0.11

  dbt_hive:
    image: ghcr.io/dbt-labs/dbt-core:1.10.0b2 
    container_name: dbt_hive
    environment:
      TZ: "America/Sao_Paulo" 
    volumes:
      - ./dbt:/usr/app/dbt  
    working_dir: /usr/app/dbt
    entrypoint: /bin/sh
    command: -c "apt-get update && \
                 apt-get install -y gcc g++ libkrb5-dev && \
                 pip install dbt-hive && \
                 tail -f /dev/null"
    networks:
        airflow-net:
          ipv4_address: 172.25.0.12

volumes:
  postgres-db-volume:
  datalake:
    driver: local
