default:
  outputs:
    dev:
      type: hive
      # Add sample credentials here, like:
      host: 172.28.0.15
      port: 10000
      username: hadoop
      password: hadoop
      schema: youtube  # <== Esse campo precisa ser uma string válida
      database: youtube  # também pode ser necessário para Hive/Spark
  target: dev
