models:
  - name: prata_video
    description: "Tabela com tratamento de dados da camada prata com tratamentos basicos (espaçamento, duplicidade de dados), já são dados limpos"
    columns:
      - name: total_visualizacoes
        description: "Total de visualizações do vídeo"
        data_type: integer
      - name: total_likes
        description: "Total de likes do vídeo"
        data_type: integer
      - name: total_favoritos
        description: "Total de favoritos do vídeo"
        data_type: integer
      - name: total_comentarios
        description: "Total de comentários do vídeo"
        data_type: integer
      - name: nome_canal
        description: "Nome do canal do youtube"
        data_type: string
      - name: titulo_video
        description: "título do vídeo do youtube"
        data_type: string
      - name: assunto
        description: "Assunto de pesquisa do vídeo"
        data_type : varchar(100)
      - name: ano
        description: "ano de pesquisa do vídeo"
        data_type: integer
      - name: mes
        description: "mês de pesquisa do vídeo"
        data_type: integer
      - name: dia
        description: "Dia da coleta"
        data_type: integer
      - name: semana
        description: "Dia da semana da coleta"
        data_type: string
      - name: id_canal
        description: "ID do canal no youtube"
        data_type: varchar(300)
      - name: id_video
        description: "Id do vídeo no youtube"
        data_type: varchar(150)
