youtube_datalake:
  outputs:
    dev:
      type: hive
      # Add sample credentials here, like:
      host: 172.25.0.10
      port: 10000
      username: rodrigo
      password: rodrigo3
      schema: youtube
      database: youtube  
  target: dev
